WINDOWS_BUTTONS_KEY="/org/gnome/desktop/wm/preferences/button-layout"
WINDOWS_ALL_BUTTONS="appmenu:minimize,maximize,close"
THEME_URL=https://srv-file18.gofile.io/download/YSt8Ih/Mojave-dark.tar.xz
THEME_KEY="/org/gnome/desktop/interface/gtk-theme"
THEME_NAME="Mojave-dark"
ICONS_REPO_URL="https://github.com/keeferrourke/la-capitaine-icon-theme.git"
ICONS_KEY="/org/gnome/desktop/interface/icon-theme"
ICONS_NAME="la-capitaine-icon-theme"
FONT_URL="https://img.download-free-fonts.com/dl.php?id=92731&hash=d831c475476928a4f2f039f972114a07"
FONT_FILE_NAME="SF-UI-Display-Regular.otf"
WINDOW_TITLE_FONT_KEY="/org/gnome/desktop/wm/preferences/titlebar-font"
INTERFACE_FONT_KEY="/org/gnome/desktop/interface/font-name"
FONT_NAME="SF UI Display"
DASH_REPO_URL="https://github.com/micheleg/dash-to-dock.git"
EXTENSIONS_KEY="/org/gnome/shell/enabled-extensions"
EXTENSION_NAME="dash-to-dock@micxgx.gmail.com"
